New PlatformIO listener client
josephdadams/TallyArbiter pull request #358
Opened 2022-01-25 00:04 UTC by MatteoGheza

I wrote this new listener client to migrate every ESP32/ESP8266-based listener client to the same codebase, and for using PlatformIO.
It's compatible with the Arduino IDE (currently, renaming a file is needed, fixing this soon), and it support build configuration.

Every feature/piece of code is configurable (WiP), so you can enable or disable certain features on a custom build, for example, enabling tally light status output on the M5Atom (turning on a GpIO pin on bus status).

### Why did I do this?
There are 4 different firmwares for M5Atom and similar devices, and maintaining them is becoming a nightmare.
There are a lot of PR, and when a listener is update, we should apply the same patch (or similar) to the other 3.
Using PlatformIO, configuring build flags and running tests, or even emulations, is easier.
PlatformIO has a build cache, and it uses them when you re-compile the code after a change. With this cache, compiling requires only a few seconds.

### TODOs:

- [x] Connect to server and handle device status change
- [x] Save preferences and display settings into the WiFi selection page
- [X] Implement tally status GPIO output
- [ ] Rename main file to support Arduino IDE
- [ ] MDNS TallyArbiter server discovery
- [ ] Implement M5Stick and similar platforms looking at the old listeners
- [ ] "Porting" PRs-added features here

2022-01-25 01:04 UTC, wrldtvlr commented
Cool! Look forward to trying it out.

2022-01-25 01:53 UTC, josephdadams commented
Amazing as always, @MatteoGheza !

2022-01-25 09:18 UTC, mg-1999 commented
Looks awesome! Hit me up when you need testing on the clients.

2022-01-27 08:52 UTC, mg-1999 commented
How do you plan on adding all the features of the different clients without the 'main' file getting complicated to work in?

2022-01-28 17:04 UTC, MatteoGheza commented
> How do you plan on adding all the features of the different clients without the 'main' file getting complicated to work in?

IDK. I tried to split the code into different files.
Functions in main.cpp currently:
- setAdafruitNeoPixelColor if Adafruit NeoPixel is enabled (since you should be able to use NeoPixel on a TTGO or an M5Stack, for example)
- event_* for every WebSocket event
- socketIOEvent for parsing Socket.IO events and socketIOConnEvent for Websocket connection
- saveParamCallback since it's used only in main.cpp
- setup() and loop()

I think that I should add more comments.

2022-01-28 22:07 UTC, mg-1999 commented
Looks like a good start.

I see that you are putting listener specific code in a separate file. And then calling listener specific 'initialise' and 'process tally data'  from the main file if they are enabled? 

Smart! Good to also document how to add listener clients with maybe an example client?

2022-02-07 21:22 UTC, JTF4 requested changes
I flashed the listener to one of my M5 Stick c Pluses and it get stuck in booting because WiFi manager still has stored settings from the other version of the software. 

I think that it needs to have a way of having its WiFi credentials and other settings reset to keep it from getting stuck in a boot loop.

2022-02-08 08:09 UTC, MatteoGheza commented
> I flashed the listener to one of my M5 Stick c Pluses and it get stuck in booting because WiFi manager still has stored settings from the other version of the software. 
> 
> I think that it needs to have a way of having its WiFi credentials and other settings reset to keep it from getting stuck in a boot loop.

I implemented a reset menu, but it works only when the device is configured (no WiFi configuration).
I tested it a lot on the TTGO.
Currently, if you click the button once, it opens the info page.
If you click it twice, it opens a page with the IP Address of the device and you can go to the settings web page (,for configuring WiFi, TA server and updating the device OTA).
If you long-press it, then you long-press it again, the device will reset.

2022-02-08 08:40 UTC, mg-1999 commented
Both option sound like a solid idea.

2022-02-08 14:23 UTC, hrueger approved these changes
To be honest, I don't know embedded at all, so I'm just gonna approve this 😀👍

2022-02-08 15:11 UTC, MatteoGheza commented
> I flashed the listener to one of my M5 Stick c Pluses and it get stuck in booting because WiFi manager still has stored settings from the other version of the software.
> 
> I think that it needs to have a way of having its WiFi credentials and other settings reset to keep it from getting stuck in a boot loop.

Done. Now, for resetting the device if it isn't configured, you should press (without releasing) the menu button (M5 button in this case) while turning on the device.

2022-03-02 19:34 UTC, mattv8 commented
I love this, thank you for taking this on @MatteoGheza! I'll bring in my initial discussion #269 here for context. Let me take a look at this and see if I can yield any suggestions.

2022-03-14 21:22 UTC, JTF4 approved these changes
Did some quick tests on my M5StickC and C+ devices. Looks like it works great!

2022-03-14 21:22 UTC, JTF4 commented
Sorry it took a month to get this review in. Life got super busy and I'm just getting back to TA

2022-03-15 18:19 UTC, mattv8 commented
> Sorry it took a month to get this review in. Life got super busy and I'm just getting back to TA

@JTF4 I know the feeling! 😅

2022-03-16 16:06 UTC, MatteoGheza commented
> Sorry it took a month to get this review in. Life got super busy and I'm just getting back to TA

It's the same for me...

2022-05-13 13:04 UTC, MatteoGheza commented
Can someone help me testing this and writing documentation (I only documented the build flags)?
This should be prod-ready.

2022-05-18 19:49 UTC, mattv8 commented
@MatteoGheza I may have some time to look into testing/documentation. I'm still currently working on my custom tally PCB (working on v2), so I'm hoping to adapt this to it and test this PR in the process.

2022-05-19 15:56 UTC, MatteoGheza commented
> @MatteoGheza I may have some time to look into testing/documentation. I'm still currently working on my custom tally PCB (working on v2), so I'm hoping to adapt this to it and test this PR in the process.

Thanks. When everythings works well, we should implement an update system.

2023-11-10 02:15 UTC, MrFobwatch commented
Hey, I just discovered this program today and I am a big fan of PlatformIO. I decided to clone the repo and try and build code and got some errors. After doing some digging I found the issue is due to a breaking change in ArduinoJSON 

https://arduinojson.org/news/2022/12/26/arduinojson-6-20-0/#removed-support-for-char-and-char

I am still learning my way around the source so I am not sure of where all this effects but the fix I used in the short term to get the code to build is to modify platformio.ini to force version 6.18.5
`bblanchon/ArduinoJson@=6.18.5`

2023-12-14 08:30 UTC, JTF4 commented
I think it should be a relatively easy fix. I'll have to see if I've got time to look into it.

2023-12-29 19:32 UTC, Jocke4f commented
What is the status of this PR? Trying to understand if there is something that I can help with.

2025-04-30 03:22 UTC, closed without merging