BUGFIX: Custom listenerClient API
josephdadams/TallyArbiter pull request #393
Opened 2022-03-02 19:44 UTC by mattv8

This PR seeks to fix a bug I found with the Custom listenerClient API. Current open issue can be found here: #305

2022-03-14 20:38 UTC, JTF4 commented
I think this looks good. However, I'm going to do some digging to see why the JSON object is not parsed at the beginning to make sure we don't have a bigger issue.

2022-03-14 20:54 UTC, JTF4 requested changes

2022-03-14 20:54 UTC, JTF4 commented on src/index.ts
> +			obj = JSON.parse(String(obj)); //Re-parse JSON
I would change this to 

`if(typeof obj !== 'object' && obj !== null) {
     logger(`Received JSON object: ${obj}`, 'info-quiet');
     obj = JSON.parse(String(obj)); //Re-parse JSON
}`

That way it does not parse an already parsed JSON object

2022-03-15 15:24 UTC, JTF4 commented
@mattv8 if you can get this finished up today, I can get it included in the new beta release later today

2022-03-15 16:50 UTC, mattv8 commented
Good to go @JTF4. I wanted to take the time to verify with my software and listener clients first. Great suggestion to add a check before reparsing.

Be aware, this may also be an issue for the `listener_reassign_object` function as well, however we have the `listener_reassign` which doesn't take a JSON object-- that's been working well for my purposes.

2022-03-15 18:33 UTC, JTF4 approved these changes
Looks great! I'll test the other two functions you're referring to and see what they do

2022-03-18 03:41 UTC, merged